# Reference image
FROM docker.elastic.co/kibana/kibana:8.19.15@sha256:e1ea4d12bfa32fd2281e2a2df48b429f803d6698fc6d7d9ecb9aa39a55145648

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/wydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/wydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-kibana"
LABEL org.opencontainers.image.url="https://github.com/wydler/parsedmarc-docker"


