# Reference image
FROM wydler/logrotate:1.2.3@sha256:f63684fbf0e65ac91663c36a60be83a1d93c70643c626fd5153e812695eca3f5

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/wydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/wydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-logrotate"
LABEL org.opencontainers.image.url="https://github.com/wydler/parsedmarc-docker"
